name: "Pipeline Security Engine"
description: "Visibility and control over all the network activity from your pipeline."
inputs:
  github-token:
    description: "github token"
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
  post: "cleanup/index.js"
