name: "InvisiRisk - PSE Action"
description: "Runs InvisiRisk - PSE"
inputs:
  github-token:
    description: "github token"
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
  post: "cleanup/index.js"
